# Generated by Django 4.1.4 on 2023-01-01 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('task', models.CharField(max_length=300, verbose_name='Задача')),
                ('teg', models.CharField(choices=[('💻Работа', '💻Работа'), ('🏆Спорт', '🏆Спорт'), ('👫Семья', '👫Семья'), ('🎧Личная', '🎧Личная'), ('🎓Обучение', '🎓Обучение'), ('🏰Дом', '🏰Дом'), ('🧬Здоровье', '🧬Здоровье'), ('🌋Путешествия', '🌋Путешествия'), ('🎮Отдых', '🎮Отдых'), ('🍕Покупки', '🍕Покупки'), ('🎪Мероприятия', '🎪Мероприятия'), ('🚇Другое', '🚇Другое'), ('', '')], default='', max_length=12, verbose_name='Тег')),
                ('date', models.DateField(verbose_name='Дата Задачи')),
                ('is_global', models.BooleanField(verbose_name='Отнести к задаче')),
                ('global_task', models.CharField(blank=True, max_length=100, verbose_name='Глобальная задача')),
                ('is_archive', models.BooleanField(verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
