# Generated by Django 4.1.4 on 2022-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Имя')),
                ('title', models.TextField(verbose_name='Название задачи')),
                ('task', models.TextField(verbose_name='Задача')),
                ('teg', models.TextField(verbose_name='Тэг')),
                ('date', models.DateField(verbose_name='Дата Задачи')),
                ('is_global', models.BooleanField(verbose_name='is_global_task')),
                ('global_task', models.TextField(verbose_name='Глобальная задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
